### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by loveklmn** [moosin76/ez-tiptap#1]
Thanks for this project.

I was wondering how to use the component from scratch since lots of styles are missing when I tried it.

See here for the detailed missing problem. https://codesandbox.io/s/cold-https-ie33v?file=/src/App.vue:607-620

**Comment by moosin76** [comment]
import Vue  from "vue";
import EzTiptap from "@ezvue/ez-tiptap-editor";
import "@ezvue/ez-tiptap-editor/dist/ez-tiptap.min.css"

Vue.component("EzTiptap", EzTiptap);

If the style cannot be applied, copy the css file from the above location and apply it to the project.
